import { Inter } from "next/font/google";
import { Atma } from "next/font/google";
import "./globals.css";
const atma = Atma({subsets:["latin"],weight:['300','400','500','600','700'],display:'swap'})
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${atma.className}`}>{children}</body>
    </html>
  );
}
